### ISSUE TITLE
Compatibility with RadarZoom

### ISSUE THREAD

**Issue by throwitaway99** [Zaggy1024/LC_TwoRadarMaps#1]
Currently, if you use TwoRadarMaps with RadarZoom, the radar generated in the terminal will not respect the zoom option selected (it will instead stay to the default, and the zoom button will have no effect on it).. Would it be possible to introduce compatibility?

**Comment by Zaggy1024** [comment]
Since this mod decouples the two map displays, it feels to me like the expected behavior would be for the zoom on the main monitor not to affect the terminal.

Perhaps instead of coupling the zoom level, I should add an option to enable a command zooming in and out of the terminal map. However, I would it rather jump to the zoom level with the green flashing animation that is used when switching targets instead of using the smooth zoom animation that RadarZoom implements, so they would perhaps look out of place next to each other. The animation style could be another config option, though.

What are your thoughts?

**Comment by throwitaway99** [comment]
That honestly sounds perfect! In my mind, just having the sort of zoom functionality was what I was looking for, since that was something I enjoyed from the RadarZoom mod. I think it would be nice if you could set a default, so for instance I could set it to default to being zoomed out past the vanilla default (preferably with some sort of number values, to really dial it in.)
