### ISSUE TITLE
Incompatible with darmuhsTerminalStuff

### ISSUE THREAD

**Issue by throwitaway99** [Zaggy1024/LC_TwoRadarMaps#2]
When using both mods in conjunction, it seems that TwoRadarMaps completely breaks. The radar view is no longer independent, and running any of the plethora of zoom commands will break the radar entirely. This isn't new to this update - I've tested on previous versions and the same issue arises.

Just as a side-note unrelated to the issue, I love the implementation of the zoom feature, it is very intuitive and exactly as I wished for, just a shame that darmuhsTerminalStuff breaks the mod.

**Comment by Zaggy1024** [comment]
It looks like this is an issue (kind of) on their end, since [they grab the map texture from the main monitor's material](https://github.com/darmuh/TerminalStuff/blob/2.2.X/DarmuhsTerminalCommands/LeaveTerminal.cs#L997) instead of the texture referenced by the `view monitor` terminal node. From what I can tell, the `switch` command still applies to the terminal map instance that my mod creates, so it appears to do nothing.

I could potentially "fix" this by writing a patch for DarmuhsTerminalCommands that replaces all references to `StartOfRound.Instance.mapScreen` with this mod's map renderer (which would also cause `tp` and `itp` to select the terminal's map target). Alternatively, darmuh's mod could use the `ManualCameraRenderer` component attached to the `Terminal` if it is present. Problem is, then you end up with the body cam display being mismatched with the map display when viewing the `minimap` mode. 

To display a body cam in the terminal attached to TwoRadarMaps's map renderer would require compatibility between the body cam mod, darmuh's mod and this one. I am actually working on a new body cam mod myself, so that's not a huge issue hopefully.

The best solution I can think of is if my body cam mod provides a command that displays the body cam in the terminal and follows the target of the terminal map provided by TwoRadarMaps, then darmuh's mod could take the display textures from the terminal nodes for both the radar map and the body cam. It can fall back to the texture displayed on the secondary monitor used by (most?) body cam mods if the body cam command is not found.

**Comment by pedro9006** [comment]
@Zaggy1024 I tried to use Darmuh's Terminal mod, since that's the only one that I knew could keep the terminal on after getting off it. Although, since it doesn't work, do you happen to know any alternative mods that can serve the same function?

**Comment by Zaggy1024** [comment]
Unfortunately, the only one I've actually tested in particular is [Lethal Company Enhancer](https://thunderstore.io/c/lethal-company/p/Mom_Llama/Lethal_Company_Enhancer/), which does have other functionality included which you may not want. I couldn't tell you if there are others that do it. It's also worth noting that since this mod adds a separate map renderer, keeping the terminal and its map visible will result in a performance penalty.

**Comment by Zaggy1024** [comment]
Little update on this:
- I've refactored [OpenBodyCams](https://github.com/Zaggy1024/LC_OpenBodyCams/) to allow multiple bodycams, which gets us closer to an independent body cam for the terminal.
- I believe darmuh is working on a refactor of their mod, once that's done, compatibility with TwoRadarMaps should be easy enough. As far as getting an independent body cam working, that might take a bit more work, since OpenBodyCams is a little unproven in that regard.

**Comment by Zaggy1024** [comment]
I totally forgot to close this issue, but compatibility has been integrated into Darmuh's mod a while back in its [3.0.0 update](https://github.com/darmuh/TerminalStuff/commit/eb350be89727f6dc7f6b2fe38b17d876b385b709).
