### ISSUE TITLE
Zoom function conflicts with EnhancedRadarBooster

### ISSUE THREAD

**Issue by Freelancerjw** [Zaggy1024/LC_TwoRadarMaps#4]
Just installed TwoRadarMaps again after not using it for awhile and noticed the zoom function which I thought was cool! However, when I tried to use it, I could not get it to work. The terminal screen flashes green like it was trying to do something, but the zoom level doesn't actually change. I only know just enough coding to be dangerous, but I feel like it _might_ be a conflict with EnhancedRadarBooster since it does have zoom level function for the radar boosters but I don't have any evidence to back that up so I dunno. Just thought you would like to know!

Log:
[LC Log 2152024.txt](https://github.com/Zaggy1024/LC_TwoRadarMaps/files/14305774/LC.Log.2152024.txt)

Profile Code:
018db025-38ef-16c0-b355-40a8202c6768

Mods:
BepInEx-BepInExPack-5.4.2100
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
Rune580-LethalCompany_InputUtils-0.6.3
NotAtomicBomb-TerminalApi-1.5.1
AlexCodesGames-AdditionalContentFramework-1.0.3
Ozone-Runtime_Netcode_Patcher-0.2.5
jockie-LethalExpansionCore-1.3.15
IAmBatby-LethalLevelLoader-1.1.6
AudioKnight-Starlancer-0.6.0
AudioKnight-StarlancerAIFix-1.2.0
AudioKnight-StarlancerMusic-1.1.0
sfDesat-ExpansionAssets-1.1.0
NiceHairs-NuclearLib-1.0.4
AinaVT-LethalConfig-1.3.4
no00ob-LCSoundTool-1.5.1
Clementinise-CustomSounds-2.3.2
Rattenbonkers-TVLoader-1.1.1
Owen3H-CSync-1.0.8
Hardy-LCMaxSoundsFix-1.0.0
malco-Lategame_Upgrades-3.1.1
Evaisa-LethalThings-0.9.4
notnotnotswipez-MoreCompany-1.8.1
loaforc-FacilityMeltdown-2.3.0
monkes_mods-JumpDelayPatch-1.0.1
Zaggy1024-OpenBodyCams-1.2.0
Zaggy1024-TwoRadarMaps-1.2.0
KlutzyBubbles-BetterEmotes-1.4.5
FlipMods-TooManyEmotes-1.9.1
KlutzyBubbles-InfiniteEmote-1.3.3
companyemployee-EquipmentCompany-1.3.0
PotatoePet-AdvancedCompany-1.1.1
Verity-TooManySuits-1.0.5
x753-More_Suits-1.4.1
AlexCodesGames-AdditionalSuits-2.0.0
GhostbustingTrio-CustomFunSuits-1.8.3
Norman-GlowStickSuits-1.0.4
Hexnet111-SuitSaver-1.1.4
HomelessGinger-MaskedEnemyOverhaul-3.1.2
kuba6000-LC_Masked_Fix-0.0.2
RugbugRedfern-Skinwalkers-4.0.1
FlipMods-FasterItemDropship-1.2.1
Midge-PushCompany-1.2.0
Suskitech-AlwaysHearActiveWalkies-1.4.4
TheBeeTeam-PersistentPurchases-1.2.0
MrHydralisk-EnhancedRadarBooster-1.6.2
NutNutty-SellTracker-1.2.1
quackandcheese-MirrorDecor-1.3.2
NiceHairs-Symbiosis-1.0.5
Electric131-OuijaBoard-1.5.3
Jordo-NeedyCats-1.1.1
Pinta-PintoBoy-1.0.4
AllToasters-SpectateEnemies-2.3.1
EliteMasterEric-SlimeTamingFix-1.0.2
TwinDimensionalProductions-CoilHeadStare-1.0.6
Cursed-Lethal_TV_-1.0.5
Yoshify-DiscJockey-1.2.1
taffyko-BetterSprayPaint-2.0.2
SirTyler-BetterTeleporter-1.2.2
Piggy-ShowCapacity-1.0.9
ShaosilGaming-GeneralImprovements-1.1.9
ViViKo-ItemClippingFix-1.1.3
Hamunii-JetpackFallFix-2.0.1
FlipMods-MoreBlood-1.0.2
LethalResonance-LETHALRESONANCE-4.0.8
LethalResonance-LETHAL_RESONANCE_MELTDOWN-1.1.6
LethalResonance-LETHALRESONANCE_TheForgottenScanner-1.0.1
BGN-PizzaTowerEscapeMusic-2.3.0
Sant5050-Buy_Any_Ship_Decoration-1.0.0
Justice69-ImmersiveScraps-1.1.9
Dev1A3-ScannableCodes-1.0.2
darmuh-ghostCodes-1.5.1
stormytuna-RouteRandom-1.3.1
Sligili-HDLethalCompany-1.5.6
FlipMods-ObjectVolumeController-1.0.4
Hamunii-JetpackWarning-2.2.0
BlueAmulet-LCBetterClock-1.0.3
Monkeytype-HideChat-1.0.0
EliteMasterEric-Coroner-1.6.0
5Bit-VoiceHUD-1.0.4
malco-Terminal_TP-1.0.1
NotAtomicBomb-Terminal_History-1.0.4
FutureSavior-Hold_Scan_Button-1.1.1
zatrit-MouseBind-1.0.0
PopleZoo-BetterItemScan-3.0.1
akechii-DiscountAlert-2.3.0
sunnobunno-YippeeMod-1.2.3
Zingar-Atlas_Abyss-1.1.8
Zingar-SecretLabs-3.3.7
scoopy-Scoopys_Variety_Mod-1.2.0
Major_And_Skiz-MoreInteriors-2.5.0
Dantor-Dantors_Mental_Hospital-1.0.3
Badham_Mods-SCPFoundationDungeon-2.3.1
AudioKnight-StarlancerMoons-0.5.7
Magic_Wesley-Infernis-2.0.1
Magic_Wesley-Acidir-3.0.0
Magic_Wesley-Etern-2.0.0
Magic_Wesley-Atlantica-1.0.2
Magic_Wesley-Polarus-1.0.1
Magic_Wesley-Asteroid13-1.0.1
Magic_Wesley-Gratar-1.0.0
jaspercreations-Scopophobia-1.1.1
PloufJPEG-CompanyCreatures-0.2.0
x753-Peepers-0.9.6

**Comment by Zaggy1024** [comment]
Yeah, unfortunately that functionality just inherently conflicts with TwoRadarMaps, in two ways:
- Both mods set the orthographic size of the map camera. EnhancedRadarBooster is setting it every frame, so that overrides what my mod does completely.
- It also changes the near and far plane distances. I'm not sure why, as that's not necessary when changing zoom, but maybe it's so that you can see more levels of the interior at once. However, this also necessitates changing the UI canvas's depth in the map camera, but since vanilla assumes there is only one of those, it sets the one for the main map camera instead of the terminal map camera, causing the UI to become invisible in the terminal.

(see [MCR_MapCameraFocusOnPosition_Postfix()](https://github.com/MrHydralisk/Lethal-Company-Enhanced-Radar-Booster/blob/main/EnhancedRadarBooster/HarmonyPatches.cs#L41-L45))

I think that compatibility between the two would require one mod to implement explicit support for the other. I'm thinking _maybe_ the easiest solution is for me to run some transpilers over the relevant function in their mod.

**Comment by Freelancerjw** [comment]
Hmm. I've been wondering why the maps seemed to be harder to read codes sometimes.....

I ended up disabling "MapRangeRBEnabled" setting in EnhancedRadarBooster's config and it seems to have fixed the issue!

**Comment by Zaggy1024** [comment]
I believe the codes being harder to read would just come down to the vastly increased field of view on the camera. I'm not sure if the canvas depth affects that, since the camera is orthographic, I wouldn't think so.

And yeah, disabling that option should do it for TwoRadarMaps zoom to function. I'll try that transpiling fix though, it shouldn't be difficult to do, since I already have most of the transpilers I need.
